model:
  name: RadSam
  task_name: RadSam-vit-B
  work_dir: ./parameters


dataset:
  start_idx: 200
  end_idx: 400
  img_dir: "/kaggle/input/radium-data/x-train-200-400"
  masks_path: "/kaggle/input/radium-data/masks_200_400.pkl"
  pnts_path: "/kaggle/input/radium-data/pnts_200_400.pkl"


training:
  device: "cuda"
  model_type: "vit_b"
  checkpoint: "/kaggle/input/radium-data/sam_vit_b_01ec64.pth"
  lr: 0.0001
  weight_decay: 0.01
  num_epochs: 10
  tr_npy_path: 
  batch_size: 4
  num_workers: 1
  resume: False
  use_amp: False
  use_wandb: True
  freeze_encoder: True
  


