model:
  name: RadSam
  task_name: RadSam-vit-B
  work_dir: ./parameters


dataset:
  start_idx: 40
  end_idx: 400
  img_dir: "/kaggle/input/radium-data/x-train-0-400"
  masks_path: "/kaggle/input/radium-data/masks_40_400.pkl"
  pnts_path: "/kaggle/input/radium-data/pnts_40_400.pkl"
  val_path: "/kaggle/input/radium-data/y_val_40.npy"


training:
  device: "cuda"
  model_type: "vit_b"
  checkpoint: "/kaggle/input/radium-data/sam_vit_b_01ec64.pth"
  lr: 0.001
  weight_decay: 0.01
  num_epochs: 25
  batch_size: 4
  num_workers: 1
  resume: False
  use_amp: False
  use_wandb: True
  freeze_encoder: True
  


